src/Entity/Address.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AddressRepository")
 */
class Address
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $number;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $street_1;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $street_2;

    /**
     * @ORM\Column(type="integer")
     */
    private $zip_code;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $city;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\User", mappedBy="address")
     */
    private $users;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Donation", mappedBy="address")
     */
    private $donations;

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->donations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumber(): ?int
    {
        return $this->number;
    }

    public function setNumber(?int $number): self
    {
        $this->number = $number;

        return $this;
    }

    public function getStreet1(): ?string
    {
        return $this->street_1;
    }

    public function setStreet1(string $street_1): self
    {
        $this->street_1 = $street_1;

        return $this;
    }

    public function getStreet2(): ?string
    {
        return $this->street_2;
    }

    public function setStreet2(?string $street_2): self
    {
        $this->street_2 = $street_2;

        return $this;
    }

    public function getZipCode(): ?int
    {
        return $this->zip_code;
    }

    public function setZipCode(int $zip_code): self
    {
        $this->zip_code = $zip_code;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->setAddress($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->contains($user)) {
            $this->users->removeElement($user);
            // set the owning side to null (unless already changed)
            if ($user->getAddress() === $this) {
                $user->setAddress(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Donation[]
     */
    public function getDonations(): Collection
    {
        return $this->donations;
    }

    public function addDonation(Donation $donation): self
    {
        if (!$this->donations->contains($donation)) {
            $this->donations[] = $donation;
            $donation->setAddress($this);
        }

        return $this;
    }

    public function removeDonation(Donation $donation): self
    {
        if ($this->donations->contains($donation)) {
            $this->donations->removeElement($donation);
            // set the owning side to null (unless already changed)
            if ($donation->getAddress() === $this) {
                $donation->setAddress(null);
            }
        }

        return $this;
    }

}

src/Entity/Donation.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DonationRepository")
 */
class Donation
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $picture;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Status", inversedBy="donations")
     */
    private $status;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Address", inversedBy="donations")
     */
    private $address;


    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User", inversedBy="donations")
     */
    private $users;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Product", mappedBy="donation")
     */
    private $products;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $isVoted;


    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->products = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getPicture()
    {
        return $this->picture;
    }

    public function setPicture($picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getStatus(): ?Status
    {
        return $this->status;
    }

    public function setStatus(?Status $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getAddress(): ?Address
    {
        return $this->address;
    }

    public function setAddress(?Address $address): self
    {
        $this->address = $address;

        return $this;
    }


    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->contains($user)) {
            $this->users->removeElement($user);
        }

        return $this;
    }

    /**
     * @return Collection|Product[]
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
            $product->setDonation($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        if ($this->products->contains($product)) {
            $this->products->removeElement($product);
            // set the owning side to null (unless already changed)
            if ($product->getDonation() === $this) {
                $product->setDonation(null);
            }
        }

        return $this;
    }

    public function getIsVoted(): ?int
    {
        return $this->isVoted;
    }

    public function setIsVoted(?int $isVoted): self
    {
        $this->isVoted = $isVoted;

        return $this;
    }

}

src/Entity/Product.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 */
class Product
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantity;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $expiry_date;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="products")
     */
    private $category;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Donation", inversedBy="products")
     */
    private $donation;
    

    public function __construct()
    {
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getExpiryDate(): ?\DateTimeInterface
    {
        return $this->expiry_date;
    }

    public function setExpiryDate(\DateTimeInterface $expiry_date): self
    {
        $this->expiry_date = $expiry_date;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getDonation(): ?Donation
    {
        return $this->donation;
    }

    public function setDonation(?Donation $donation): self
    {
        $this->donation = $donation;

        return $this;
    }

}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $company;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $phone_number;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $rating;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_active;

    /**
     * @ORM\Column(type="integer")
     */
    private $points;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Role", inversedBy="users")
     */
    private $role;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Reward", inversedBy="users")
     */
    private $reward;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Address", inversedBy="users")
     */
    private $address;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Donation", mappedBy="users")
     */
    private $donations;

    public function __construct()
    {
        $this->is_active = true;
        $this->donations = new ArrayCollection();
        $this->points = 0;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        // $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = $this->getRole()->getCode();

        return array_unique($roles);

        // return [$this->getRole()->getCode()]; //je doit retourner des chaine de caractere dans mon tableau
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(?string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getCompany(): ?string
    {
        return $this->company;
    }

    public function setCompany(string $company): self
    {
        $this->company = $company;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(string $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getRating(): ?int
    {
        return $this->rating;
    }

    public function setRating(?int $rating): self
    {
        $this->rating = $rating;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function getPoints(): ?int
    {
        return $this->points;
    }

    public function setPoints(int $points): self
    {
        $this->points = $points;

        return $this;
    }

    public function getRole(): ?Role
    {
        return $this->role;
    }

    public function setRole(?Role $role): self
    {
        $this->role = $role;

        return $this;
    }

    public function getReward(): ?Reward
    {
        return $this->reward;
    }

    public function setReward(?Reward $reward): self
    {
        $this->reward = $reward;

        return $this;
    }

    public function getAddress(): ?Address
    {
        return $this->address;
    }

    public function setAddress(?Address $address): self
    {
        $this->address = $address;

        return $this;
    }

    /**
     * @return Collection|Donation[]
     */
    public function getDonations(): Collection
    {
        return $this->donations;
    }

    public function addDonation(Donation $donation): self
    {
        if (!$this->donations->contains($donation)) {
            $this->donations[] = $donation;
            $donation->addUser($this);
        }

        return $this;
    }

    public function removeDonation(Donation $donation): self
    {
        if ($this->donations->contains($donation)) {
            $this->donations->removeElement($donation);
            $donation->removeUser($this);
        }

        return $this;
    }
}

templates/donation/filtered-list.html.twig
{% extends 'base.html.twig' %}

{% block title %}liste des dons{% endblock %}

{% block picture_header %}{% endblock %}

{% block body %}
{# ici il faut charger le formulaire de tri => inclure un template tierce#}
<div class="form-inline">
{{ include('donation/_form-categories.html.twig') }}
<a href="{{path('donation_list')}}" class="btn btn-outline-secondary"> <i class="fas fa-times-circle"></i> Supprimer le filtre</a>
</div>

<h2> Les dons postés dans la catégorie {{category}}</h2>
<div class="row mt-3">
{% for donation in donations %}
    <div class="col-md-6 col-12 my-2">
            <div class="card h-100">
                <div class="card-body">
                    {# {{ asset('uploads/pictures/' ~ donation.picture) }} #}
                    <img src="{{ asset('uploads/pictures/' ~ donation.picture) }}" class="card-img regul-size" alt="image du don">
                    
                    <h3 class="card-title">
                        {{donation.title}}
                        {% if "Dispo" == donation.status.name %}
                            <img class="mainpoper" src="{{asset('pictures/status_dispo.png')}} " alt="Don disponible">
                            <div class="subpoper">Ce don est disponible</div>
                        {% elseif "Réservé" == donation.status.name %}
                            <img class="mainpoper" src="{{asset('pictures/status_reserve.png')}} " alt="Don déjà réservé">                         
                            <div class="subpoper">Ce don est réservé</div>
                        {% endif %}
                    </h3>
                    <p class="card-text">Crée le {{donation.createdAt|date("d/m/Y")}}</p>
                    <p class="card-text">À {{donation.address.city}} ({{donation.address.zipcode}})</p>
                    {% if expiryDateArray[donation.id] is defined %}
                        <p class="card-text">Date de péremption : {{ expiryDateArray[donation.id]|date("d/m/Y") }}</p>
                    {% endif %}
                    <a href="{{path('donation_show', {'id': donation.id})}}" class="btn btn-primary">Plus d'infos</a>
                </div>
            </div>
        </div>
{% endfor %}
</div>
<div class="pagination col-md-5 mx-auto mt-4">
    {{ knp_pagination_render(donations) }}
</div>
{% endblock %}

templates/donation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Faire un don{% endblock %}

{% block picture_header %}{% endblock %}

{% block body %}
<h2 class="p-3 text-center mb-5">Faire un don</h2>

{{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}

    {{ form_row(form.title, { 'id': 'title-donation'  }) }}
    {{ form_row(form.picture, { 'id': 'donation-pic' }) }}
    {# <label class="custom-file-label" for="donation-pic">Choose file...</label> #}

    {# Affichage formulaire d'ajout d'adresse #}
    <div class="card bg-light mb-4">
        <div class="card-header">
            <h5>Adresse de récupération du don</h5>
        </div>
        <div class="card-body">
            <p class="card-text">
                {{app.user.address.number}} {{app.user.address.street1}} <br>         
                {{app.user.address.street2}} <br> 
                {{app.user.address.ZipCode}} {{app.user.address.city}}
            </p>
            <button class="btn btn-link" id="showChangeAdress" >Utiliser une autre adresse </button>
            
        </div>
        <div class="card-body hide-my-form" id="changeAdress" name="newAddress">
            {# {{form_row(form.address)}} #}

            <div class="form-group">
                <label for="number">Numéro </label>
                <input type="text" class="form-control" id="number" name="number" placeholder="Numéro">
            </div>
            <div class="form-group">
                <label for="street1">Nom de la rue*</label>
                <input type="text" class="form-control" id="street1" name="street1" placeholder="Rue, Avenue, Boulevard ... " required>
            </div>
            <div class="form-group">
                <label for="street2">Complément d'adresse</label>
                <input type="text" class="form-control" id="street2" name="street2" placeholder="Complément d'adresse ">
            </div>
            <div class="form-group">
                <label for="zipCode">Code Postal*</label>
                <input type="text" class="form-control" id="zipCode" name="zipCode" placeholder="Code postal " required>
            </div>
            <div class="form-group">
                <label for="city">Ville*</label>
                <input type="text" class="form-control" id="street2" name="city" placeholder=" Ville " required>
            </div>
                
        </div>
    </div>

    {# Affichage formulaire d'ajout de produit #}
    <div  id='product_list' data-prototype="{{ form_widget(form.products.vars.prototype)|e('html_attr') }}">
            {% for row in form.products %}
            <div class="card bg-light">
                <div class="card-header">
                    <h5>Description du produit</h5>
                </div>
                <div class="card-body">
                    {{ form_row(row.name, { "id": "productName"}) }}
                    {{ form_row(row.quantity, { "id": "productQuantity"}) }}
                    {{ form_row(row.category, { "id": "productCategory" }) }}
                    {{ form_row(row.expiry_date, {"id": "productDate"}) }}
                    {{ form_row(row.description, {"id": "productDescription"} ) }}
                    {# <button class="btn btn-secondary" id="btn-add-product">Enregistrer un produit</button> #}
                </div>
            </div>
        {% endfor %}
    </div>
    
{{ form_end(form) }}

{% endblock %}


{% block javascripts %}
    <script src="{{asset('js/file-name.js')}}"></script>
{% endblock %}

templates/donation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail du don{% endblock %}

{% block stylesheets %}
    {# CSS POUR LA MAP #}
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.4.0/dist/leaflet.css" />
{% endblock %}

{% block picture_header %}{% endblock %}

{% block body %}
    <div class="return-to-list">
        <p>
            <a href="{{path('donation_list')}} "> <i class="fas fa-angle-double-left"></i> Retour à la liste </a>
        </p> 
    </div>
    {# {{dump(donation)}} #}
    <h2 class="text-center">{{donation.title}} </h2>

    <section id="donation-detail-head" class="row mb-2">
        <div class="col-12 col-md-6">
            <img id="pic-donation" src="{{ asset('uploads/pictures/' ~ donation.picture) }}" class="img-fluid mb-1"  alt="Responsive image">
        </div>
        {# {{dump(app.user.id)}} #}

        <div class="col-12 col-md-6 d-flex flex-column justify-content-between">
            {% if donation.status.name != "Donné" %}
                {# Formulaire de sélection/déselection du don #}
                <div id="select-donation" class="mb-2">
                    {# si le don est déja réservé #}
                    {% if "Réservé" == donation.status.name %}
                        <p id="reserved" class="mb-3">
                            <i class="fas fa-clock"></i> Ce don est réservé
                        </p>

                            {# {{dump(app.user.id)}} #}

                        
                        {% if collector %} {# Si un collector existe #}
                                    {# {{dump(collector)}} #}
                            {% if app.user %} {# et si un utilisateur est connecté #}
                                {# si l'ID de l'utilisateur connecté est le même que celui du collector existant, on affiche le bouton qui permet de déselctionner le don #}
                                {% if app.user.id == collector.id %}
                                    {# {{dump(collector.id)}} #}
                                    <form action="{{path('donation_deselect', {'id': donation.id}, {'method' : 'POST'})}}" method="POST">
                                        
                                        <button class="btn btn-link" id="deselect">
                                            Annuler la réservation de ce don <i class="far fa-times-circle"></i>
                                        </button>
                                    </form>
                                
                                {% endif %}
                            {% endif %}                                           
                        {% endif %}
                    
                    {# si le don est disponible  #}
                    {% elseif is_granted('ROLE_ASSOC') %}
                        
                            <form action="{{path('donation_select', {'id': donation.id}, {'method' : 'POST'})}} " method="POST">
                                    
                                <button class="btn btn-link" id="select">
                                Réserver ce don <i class="far fa-check-circle"></i>
                                </button>
                            </form>   
                        {% else %}
                            Vous ne pouvez pas réserver ce don
                    {% endif %}            
                </div>
            
            {% endif %}
            
            
            {# Informations sur le donateur #}
            <div>
                <h3> Informations sur le donateur</h3>
                {# {{ dump(giver)}} #}
                <p class="font-weight-bold">
                    {{ giver.company}}
                </p>
                <p>
                    Contact : {{ giver.firstname}} {{ giver.lastname}} <br>
                    Téléphone: {{ giver.phoneNumber}} <br>
                    e-mail : {{ giver.email}} <br>
                </p>
{# {{dump(donation.status)}} #}
                <div class="d-flex flex-row align-items-center row">
                    <p class="mb-0 col-md-3 col-12 pr-0"> Note : {{giver.rating}}</p>  
                    <div class="rating rating2 m-0 w-100 col-md-9  col-12">
                    
                        <form method="post" action='{{path('donation_vote', {'id': donation.id})}}' class="d-flex flex-row-reverse flex-wrap col-10 align-items-center justify-content-end pl-0"><!--
                           -->  {% if collector %}
                                    {% if app.user %}
                                        {% if app.user.id == collector.id %}
                                            {% if donation.status.name == 'Donné' %}                                            
                                                {% if donation.isVoted == null  %}
                                                <button type="submit" class="btn btn-secondary ml-1 order-md-2 order-1 order-lg-1">Voter</button>
                                                {% else %}
                                                    <p class="h6 ml-1 order-md-2 order-1 order-lg-1">Vous avez déjà voté !</p>    
                                                {% endif %}
                                            {% endif %}
                                        {% endif %}
                                    {% endif %}
                                {% endif %}
                           <div class="order-1">
                                <!--
                                --><input name="stars" value="5" id="e5" type="radio" {{ (giver.rating) == (5) ? 'checked' }}><label for="e5">★</label><!--
                                --><input name="stars" value="4" id="e4" type="radio" {{ (giver.rating) == (4) ? 'checked' }}><label for="e4">★</label><!--
                                --><input name="stars" value="3" id="e3" type="radio" {{ (giver.rating) == (3) ? 'checked' }}><label for="e3">★</label><!--
                                --><input name="stars" value="2" id="e2" type="radio" {{ (giver.rating) == (2) ? 'checked' }}><label for="e2">★</label><!--
                                --><input name="stars" value="1" id="e1" type="radio" {{ (giver.rating) == (1) ? 'checked' }}><label for="e1">★</label><!--
                                --> 
                           </div>
                        </form>
                    </div>
                </div>
                   
                <div id="reward">
                    <img src="{{ asset('pictures/' ~ (giver.reward.picture))}} " alt="reward niveau {{giver.reward.code}}" class="img-fluid mb-2" > 
                    <p>
                       Niveau {{giver.reward.title}}
                    </p>
                </div>
            </div>
        </div>
    </section>

    <section id="donation-produits">
        <h3> Liste des produits :</h3>

        <div class="table-responsive-md">

            <table class="table">
                <thead>
                    <tr>
                    <th scope="col">Nom</th>
                    <th scope="col">Quantité</th>
                    <th scope="col">Date de péremption</th>
                    <th scope="col" class="hide">Description</th>
                    </tr>
                </thead>
                {% for product in donation.products %}
                {# {{dump(product)}} #}
                    <tr>
                        <td scope="row">{{product.name}} </td>
                        <td>{{product.quantity}}</td>
                        <td>{{product.expiryDate|date("d/m/Y")}}</td>
                        <td class="hide">{{product.description}}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </section>
    <section id ="localisation">
        {# {{ dump(donation.address.number)}} #}
        <div class="card mb-3 d-flex flex-row row">
            {# <img src="..." class="card-img-top" alt="..."> #}
            <div id="map" style='width:600px; height:400px;' class="col-12 col-md-8"></div>
            <div class="card-body col-12 col-md-4">
                <h5 class="card-title">Localisation du don </h5>
                <p class="card-text">  
                    {{ donation.address.number}} {{donation.address.street1}}
                </p>
                <p class="card-text">  
                    {{ donation.address.zipCode}} {{donation.address.city}}
                </p>
            </div>
        </div>
        {# <div id="map" style='width:600px; height:400px;'></div> #}
    </section>
    <div id="btn-return">
        <a href="{{path('donation_list')}}" class="return" > 
            Retour à la liste 
        </a>
    </div>
{% endblock %}

{% block javascripts %}
    {# JS MAP #}
    <script src="https://unpkg.com/leaflet@1.4.0/dist/leaflet.js"></script>
    <script src="{{ asset('js/map.js') }}"></script>
{% endblock %}